spring:
  application:
    name: data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
